### ISSUE TITLE
SSL issue?

### ISSUE THREAD

**Issue by ersan2501** [jeder28/NY_Restaurant_Violations#8]
I am getting some crazy error. I tried troubleshooting through command line in updating my gems, openssl, my homebrew version. Still getting this error. was something changed? I am unsure why this would be throwing this error.
/Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in`block in connect'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:923:in`connect'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/net/http.rb:852:in`start'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:736:in`buffer_open'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in`catch'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:150:in`open_uri'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:716:in `open'
    from /Users/sMoKe/.rbenv/versions/2.2.1/lib/ruby/2.2.0/open-uri.rb:34:in`open'
    from /Users/sMoKe/Desktop/dbc_stuff/phase-1-guide/challenges/NY_Restaurant_Violations/model.rb:17:in `get_all_by_city'
    from /Users/sMoKe/Desktop/dbc_stuff/phase-1-guide/challenges/NY_Restaurant_Violations/model.rb:9:in`get_best'
    from controller.rb:17:in `run'
    from controller.rb:7:in`initialize'
    from controller.rb:26:in `new'
    from controller.rb:26:in`<main>'

@walsh9 @jeder28 @gravesal

**Comment by walsh9** [comment]
weird.  this is just a guess from googling around but instead of updating maybe try `brew reinstall openssl`

**Comment by ersan2501** [comment]
the only thing i hadnt tried was reinstall. that worked. it seems, thanks. If i have some time I am going to implement the restaurant search by name and look for NYC dataset. This is actually a useful app!
